name: Auto Changelog

on:
  push:
    branches:
      - dev-Shubin

jobs:
  update_changelog:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install auto-changelog
        run: |
          poetry add auto-changelog

      - name: Run auto-changelog
        run: poetry run auto-changelog

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "Auto-update CHANGELOG.md" || exit 0
          git push
