name: Auto Changelog

on:
  push:
    branches:
      - dev-Shubin

jobs:
  update_changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: dev-Shubin

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install project dependencies
        run: poetry install --no-dev

      - name: Run auto-changelog
        run: |
          poetry run auto-changelog

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "Auto-update CHANGELOG.md" || exit 0
          git push