name: changelog

on:
  push:
    branches:
      - dev-Shubin

jobs:
  update-changelog:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Add Changes
        run: |
          git add --all
          git diff-index --quiet HEAD || git commit -m "ci: Update Changelog"

      - name: Set Git User
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Push Changes
        run: git push origin HEAD:dev-Shubin
