name: changelog

on:
  push:
    branches:
      - dev-Shubin

jobs:
  update-changelog:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          source $HOME/.poetry/env

      - name: Install Dependencies
        run: poetry install

      - name: Generate Changelog
        run: poetry run auto-changelog -o CHANGELOG.md

      - name: Add Changes
        run: |
          git add CHANGELOG.md
          git diff-index --quiet HEAD || git commit -m "ci: Update Changelog"

      - name: Set Git User
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Push Changes
        run: git push origin HEAD:dev-Shubin
