name: Test without docker
on:
  push:
    tags-ignore:
      - "!refs/tags/*"
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Upgrade pip
        run: |
          python -m pip install -U pip
          python -m pip install -U poetry
      - name: Install poetry
        run: |
          poetry add poetry-plugin-up --group dev
          poetry add pre-commit --group dev
      - name: Install dependencies
        run: |
          poetry install --with=dev,test
      - name: Run test suite
        run: |
          poetry run pytest
